// AUTO-GENERATED by scripts/gen-v3-template-files.mjs — DO NOT EDIT.
// Mirrors FILES_VERSION from packages/shared/src/lib/versions.ts so the V3
// runtime worker reports it on /api/health (same axis status.ts compares).
export const V3_RUNTIME_VERSION = '1.5.0' as const
